""" Enums for cloth categories corresponding to class labels"""

SAREE = 'saree'
WOMEN_KURTA = 'women_kurta'
LEHENGA = 'lehenga'
BLOUSE = 'blouse'
GOWNS = 'gowns'
DUPATTAS = 'dupattas'
PALAZZOS = 'palazzos'
LEGGINGS_AND_SALWARS = 'leggings_and_salwars'
DHOTI_PANTS = 'dhoti_pants'
PETTICOATS = 'petticoats'
MOJARIS_WOMEN = 'mojaris_women'
SHERWANIS = 'sherwanis'
KURTA_MEN = 'kurta_men'
MOJARIS_MEN = 'mojaris_men'
NEHRU_JACKETS = 'nehru_jackets'
